services:
  log-database:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    restart: on-failure:1
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 30s
      retries: 2
    volumes:
      - redis_data:/data
    networks:
      - raft-network

  raft-node-0:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 50031:50031
    depends_on:
      - log-database
    environment:
      - GRPC_PORT=50031
      - GRPC_MAX_WORKERS=50
      - RAFT_NODES=50031,50041,50051,50061
    networks:
      - raft-network

  raft-node-1:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 50041:50041
    depends_on:
      - log-database
    environment:
      - GRPC_PORT=50041
      - GRPC_MAX_WORKERS=50
      - RAFT_NODES=50031,50041,50051,50061
    networks:
      - raft-network

  raft-node-2:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    depends_on:
      - log-database
    environment:
      - GRPC_PORT=50051
      - GRPC_MAX_WORKERS=50
      - RAFT_NODES=50031,50041,50051,50061
    networks:
      - raft-network

  raft-node-3:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 50061:50061
    depends_on:
      - log-database
    environment:
      - GRPC_PORT=50061
      - GRPC_MAX_WORKERS=50
      - RAFT_NODES=50031,50041,50051,50061
    networks:
      - raft-network

networks:
  raft-network:
    

volumes:
  redis_data:
    
